# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-20 11:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GymUserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cognome', models.CharField(blank=True, max_length=250, null=True)),
                ('nome', models.CharField(blank=True, max_length=250, null=True)),
                ('data_nascita', models.DateField(blank=True, null=True, verbose_name='Data di nascita')),
                ('sesso', models.CharField(blank=True, choices=[('M', 'Maschio'), ('F', 'Femmina')], max_length=1, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True, verbose_name='Numero telefono')),
                ('indirizzo', models.CharField(blank=True, max_length=500, null=True)),
                ('data_inizio_iscrizione', models.DateField(blank=True, null=True, verbose_name='Data inizio iscrizione')),
                ('data_scadenza_iscrizione', models.DateField(blank=True, null=True, verbose_name='Data fine iscrizione')),
                ('ultimo_accesso', models.DateTimeField(blank=True, null=True, verbose_name='Data e ora ultimo accesso')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gym_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
