# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-12-16 16:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_contents', '0005_gallery_immaginigallerie_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='press',
            options={'verbose_name': 'Articolo press', 'verbose_name_plural': 'Articoli press'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'verbose_name': 'Filmato video', 'verbose_name_plural': 'Filmati video'},
        ),
        migrations.AddField(
            model_name='alert',
            name='contenuto',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='evento',
            name='contenuto',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='contenuto',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='notizia',
            name='contenuto',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='press',
            name='contenuto',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='contenuto',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
