# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-12-16 18:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordine', models.IntegerField(blank=True, default=0)),
                ('nome', models.CharField(max_length=80)),
                ('descrizione_breve', models.CharField(blank=True, max_length=300, null=True)),
                ('descrizione', models.TextField(blank=True, max_length=2000, null=True)),
                ('data_apertura', models.DateTimeField(auto_now=True)),
                ('immagine', models.ImageField(blank=True, null=True, upload_to='immagini')),
                ('allegato', models.FileField(blank=True, null=True, upload_to='allegati')),
                ('indirizzo', models.TextField(blank=True, max_length=2000, null=True)),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubs',
            },
        ),
    ]
