# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-20 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='bianchimro@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
