# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-19 22:14
from __future__ import unicode_literals

from django.db import migrations
from customers.models import Client
from django.conf import settings

DOMAIN_URL = settings.SERVICE_MAIN_DOMAIN

# create your public tenant
def create_first_tenant(apps, schema_editor):
    tenant = Client(domain_url=DOMAIN_URL, # don't add your port or www here! on a local server you'll want to use localhost here
                schema_name='public',
                name='Schemas Inc.',
                email='admin@gym.com',
                paid_until='2100-12-31',
                on_trial=False)
    tenant.save()


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_client_email'),
    ]

    operations = [
        migrations.RunPython(create_first_tenant)
    ]
