# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-20 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slogan', models.CharField(blank=True, max_length=100, null=True)),
                ('primary_color', models.CharField(blank=True, default='#FF0000', max_length=12, null=True)),
            ],
        ),
    ]
