# -*- coding: utf-8 -*-
# Generated by Django 1.9c1 on 2015-11-20 16:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym_config', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gymconfig',
            old_name='slogan',
            new_name='valore',
        ),
        migrations.RemoveField(
            model_name='gymconfig',
            name='primary_color',
        ),
        migrations.AddField(
            model_name='gymconfig',
            name='chiave',
            field=models.CharField(default='key', max_length=100),
            preserve_default=False,
        ),
    ]
